MOTIVATIONAL_QUOTES = (
    "A small step today is still a step away from yesterday.",
    "Start before you feel ready; readiness often follows action.",
    "Consistency turns ordinary effort into uncommon results.",
    "You do not need a perfect plan to make meaningful progress.",
    "The work you repeat becomes the person you become.",
    "A difficult chapter is not the end of the story.",
    "Momentum begins with one honest attempt.",
    "Your future is shaped by what you practice today.",
    "Progress counts even when nobody else can see it yet.",
    "Make the next choice one your future self will thank you for.",
    "Courage can be quiet; sometimes it simply says, try again.",
    "You can rest without giving up.",
    "The direction matters more than the speed.",
    "Do the next useful thing, then let momentum help.",
    "Every skill was once something its owner could not do.",
    "A setback can become information instead of a verdict.",
    "Begin with what you have and improve it as you go.",
    "Discipline is remembering what you wanted most.",
    "Today is a good day to become a little more capable.",
    "The first draft of progress is allowed to be messy.",
    "Keep the promise you made to yourself this morning.",
    "One focused hour can change the direction of a whole week.",
    "You are closer once you begin.",
    "Let the challenge teach you what comfort never could.",
    "Your pace is valid as long as you keep choosing forward.",
    "Hard days still count toward a meaningful life.",
    "Build quietly; let the results make the introduction.",
    "Confidence grows from evidence, so give yourself a small win.",
    "The habit is the achievement in disguise.",
    "There is no wasted effort when you learn from it.",
    "You can change the plan without abandoning the goal.",
    "What feels slow today may look like transformation later.",
    "Make progress simple enough that you can repeat it tomorrow.",
    "The next beginning does not need permission from the last ending.",
    "Choose improvement over proving yourself.",
    "A calm mind can still carry fierce ambition.",
    "Your attention is a vote for the life you want.",
    "Do not wait for motivation to do motivation's job.",
    "The mountain becomes manageable one deliberate step at a time.",
    "You have survived every day that once felt impossible.",
    "Good work compounds long before it becomes obvious.",
    "Turn comparison into curiosity, then return to your own path.",
    "Be patient with the version of you that is still learning.",
    "A clear no protects the things deserving your yes.",
    "The goal is not perfection; it is honest progress.",
    "Your next attempt gets to know everything the last one taught you.",
    "Create more evidence that you can trust yourself.",
    "Some days the win is simply refusing to quit.",
    "The life you want is built inside ordinary days.",
    "Focus on the action within reach, not the distance remaining.",
    "Growth often feels like uncertainty before it feels like strength.",
    "You are allowed to outgrow an old definition of success.",
    "Give today's effort enough time to become tomorrow's advantage.",
    "The best time to restart is the moment you notice you stopped.",
    "Protect your energy, then spend it on what matters.",
    "An imperfect action can teach more than a perfect intention.",
    "Make your standards kind enough to be sustainable.",
    "The next version of you is built by today's repetitions.",
    "Keep going; clarity often arrives while moving.",
    "You never lose the lesson when you choose to learn.",
)
